### ISSUE TITLE
Unable to change embed color

### ISSUE THREAD

**Issue by SweetShyGirl** [appu1232/Selfbot-for-Discord#4]
So what's the fastest way for me personally to change it by editing the source?

I really want to change it.

**Comment by appu1232** [comment]
In the file ``misc.py`` under the cogs folder, there is a method called ``embed`` and the first line reads ``em = discord.Embed(description=msg)`` Edit this to have a second parameter with the color. E.g. ``em = discord.Embed(description=msg, color=0x32441c)``

I'll add a way to specify the color when you send the message sometime in the future.

**Comment by gidoBOSSftw5731** [comment]
(just a lil addon here) it would be nice if you could do `self.embed(#FFFFFF) embed text stuff` or even change the header/footer through the cmd

**Comment by appu1232** [comment]
Hmm, I haven't implemented anything for input through the cmd and I'm hesitant because I'm sure there are people that want to run it on a server where it's a little more work to access the cmd. I will eventually add the ability to just do it with the command on discord like ``>embed [color]=#FFFFFF [description]=Hello World [image]=some image etc.`` I plan on adding a way to change the color for each type of embed too (custom cmds, google, mal, etc.)

For now I'm on hiatus from adding features to the bot because I'm fairly busy with work related projects. I'll get back to adding features like these sometime next week hopefully.

**Comment by gidoBOSSftw5731** [comment]
well, ofc have a default for everything, but for nerds options are nice
